# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: tonyxrazzor/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static/
      - media:/media
    depends_on:
    - db
  frontend:
    image: tonyxrazzor/kittygram_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: tonyxrazzor/kittygram_gateway  # Качаем с DockerHub
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles
      - media:/media
